default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'].presence || 'db' %>
  username: <%= ENV['DB_USER'].presence || 'postgres' %>
  password: <%= ENV['DB_PASSWORD'].presence || 'calendar123' %>
  port: <%= ENV['DB_PORT'].presence || '5432' %>
  pool: 5

<% db_base_name = (ENV['DB_NAME'].presence || 'calendar') %>

development: &development
  <<: *default
  database: <%= ENV['DB_NAME_DEVELOPMENT'].presence || (db_base_name + '_development') %>

test:
  <<: *default
  database: <%= ENV['DB_NAME_DEVELOPMENT'].presence || (db_base_name + '_test') %>

production:
  <<: *default
  database: <%= ENV['DB_NAME_DEVELOPMENT'].presence || (db_base_name + '_production') %>
